# Default values for delivery-varnish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  certificateAwsArn: "" # The ARN of the aws certificate used by the ALB created for this service
  htpasswdSecret: "varnish-auth" # The Kubernetes secret containing the contents of the .htpasswd file used for authentication.
  external_dns_hostname: ""
alb:
  scheme: internet-facing
  targetType: ip
elb:
  tags: ""
replicaCount: 2
image:
  repository: coco/delivery-varnish
  pullPolicy: IfNotPresent
resources:
 requests:
   memory: 80Mi
   cpu: 90m
